api/urls.py
from django.urls import path

from .views import (QuestionListAPIView, TestsListAPIView, check_answers,
                    registration)

app_name = 'api'

urlpatterns = [
    path("tests/", TestsListAPIView.as_view(), name="tests"),
    path("questions/", QuestionListAPIView.as_view(), name="questions"),
    path("check-answers/", check_answers, name="check-answers"),
    path("registration/", registration, name="registration"),
]

checkyou/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('users/', include('users.urls', namespace='users')),
    path('tests/', include('tests.urls', namespace='tests')),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import login, registration

app_name = 'users'

urlpatterns = [
    path('registration/', registration, name='registration'),
    path('login/', login, name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Schools(models.Model):
    name = models.CharField(max_length=512)

    class Meta:
        verbose_name = 'Школу'
        verbose_name_plural = 'Школы'

    def __str__(self):
        return f'{self.name}'


class Classes(models.Model):
    name = models.CharField(max_length=126)

    class Meta:
        verbose_name = 'Класс'
        verbose_name_plural = 'Классы'

    def __str__(self):
        return f'{self.name}'


class User(AbstractUser):
    surname = models.CharField(max_length=126)
    is_teacher = models.BooleanField(
        ("is teacher"),
        default=False,
        help_text=("Является пользователь учителем"))
    number_class = models.CharField(max_length=12)
    school = models.CharField(max_length=126)

    class Meta:
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользоваатели'

    def save(self, *args, **kwargs):

        if self.is_teacher:
            self.is_staff = True
            self.is_superuser = True

        super().save(*args, **kwargs)


class Subject(models.Model):
    name = models.CharField(max_length=56)

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

    def __str__(self):
        return f'{self.name}'


class Teacher(models.Model):
    name = models.CharField(max_length=126)

    class Meta:
        verbose_name = 'Учителя'
        verbose_name_plural = 'Учителя'

    def __str__(self):
        return f'{self.name}'


class Tests(models.Model):
    school = models.ForeignKey(to=Schools, on_delete=models.CASCADE)
    name = models.CharField(max_length=512)
    number_class = models.ForeignKey(to=Classes, on_delete=models.CASCADE)
    teacher = models.ForeignKey(to=Teacher, on_delete=models.CASCADE)
    subject = models.ForeignKey(to=Subject, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='test_images')

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'

    def __str__(self):
        return f'{self.school} ==  {self.number_class} == {self.subject}'


class Questions(models.Model):
    test = models.ForeignKey(Tests, on_delete=models.CASCADE, related_name='questions')
    question = models.TextField()
    answer1 = models.CharField(max_length=512)
    answer2 = models.CharField(max_length=512)
    answer3 = models.CharField(max_length=512)
    true_answer = models.CharField(max_length=512)

    def __str__(self):
        return f'{self.test.school} ==  {self.test.number_class}'

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import User


class UserRegistrationForm(UserCreationForm):

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-form', 'type': 'text', 'placeholder': 'Имя'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-form', 'type': 'text', 'placeholder': 'Фамилия'
    }))
    surname = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-form', 'type': 'text', 'placeholder': 'Отчество'
    }))
    number_class = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-form', 'type': 'text', 'placeholder': 'Класс'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-form', 'type': 'text', 'placeholder': 'Имя пользователя'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'input-form', 'type': 'email', 'placeholder': 'Электронная почта'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'input-form', 'type': 'password', 'placeholder': 'Пароль'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'input-form', 'type': 'password', 'placeholder': 'Повторите пароль'
    }))
    school = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-form', 'type': 'text', 'placeholder': 'Школа'
    }))
    is_teacher = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        'class': 'input-form', 'type': 'checkbox'
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'surname',
                  'username', 'email', 'is_teacher',
                  'number_class', 'school', 'password1',
                  'password2'
                  )


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-form', 'type': 'text', 'placeholder': 'Имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'input-form', 'type': 'password', 'placeholder': 'Пароль'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

users/views.py
from django.contrib import auth
from django.shortcuts import HttpResponseRedirect, render, reverse

from .forms import UserLoginForm, UserRegistrationForm


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))

    form = UserRegistrationForm()
    context = {
        'form': form,
        'title': 'CheckYou - Регистрация',
    }

    return render(request, 'users/registration.html', context)


def login(request):
    context = {
        'title': 'CheckYou - Вход',
    }
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect('/')

    form = UserLoginForm()
    context["form"] = form

    return render(request, 'users/login.html', context)


def index(request):
    context = {
        'title': 'CheckYou',
    }
    return render(request, 'users/index.html', context)

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/icon.png' %}">
</head>
<body>
    <header class="header-login">
        <div class="header__inner">
            <div class="header__logo">
                CheckYou
            </div>
            <nav class="nav">
                {% if not user.is_authenticated %}
                <a href="{% url 'users:login' %}" class="item">Войти</a>
                <a href="{% url 'users:registration' %}" class="item">Зарегистрироваться</a>
                {% else %}
                {% if not user.school or not user.number_class %}
                <a href="{% url 'tests:tests' user.school user.number_class %}" class="item">Тесты</a>
                {% endif %}
                <a href="{% url 'users:logout' %}" class="item">Выйти</a>
                {% endif %}
                {% if user.is_superuser or user.is_staff %}
                <a href="{% url 'admin:index'%}" class="item">Админ-панель</a>
                {% endif %}
            </nav>
        </div>
    </header>

    {% block section %} {% endblock %}
</body>
</html>

users/templates/users/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/icon.png' %}">
</head>
<body>
    <header class="header-main">
        <div class="header__inner">
            <div class="header__logo">
                CheckYou
            </div>
            <nav class="nav">
                {% if not user.is_authenticated %}
                <a href="{% url 'users:login' %}" class="item">Войти</a>
                <a href="{% url 'users:registration' %}" class="item">Зарегистрироваться</a>
                {% else %}
                {% if user.school or user.number_class %}
                <a href="{% url 'tests:tests' user.school user.number_class %}" class="item">Тесты</a>
                {% endif %}
                <a href="{% url 'users:logout' %}" class="item">Выйти</a>
                {% endif %}
                {% if user.is_superuser or user.is_staff %}
                <a href="{% url 'admin:index'%}" class="item">Админ-панель</a>
                {% endif %}
            </nav>
        </div>
        <div class="header__titles">
            <h2 class="header__suptitle">Создавай и проходи тесты</h2>
            <a href="{% static 'app/app-debug.apk' %}" download class="header__button">Скачать <br>приложение</br><br>(Android)</br></a>
        </div>
    </header>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}


{% block section %}
<section class="login">
    <div class="login-card">
        <form action="{% url 'users:login' %}" class="form-login" method="post">
            {% csrf_token %}
            <p>Вход</p>
            {{form.username}}
            {{form.password}}
            <button type="submit" class="button-form">Войти</button>
        </form>
    </div>
</section>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}


{% block section %}
<section class="registraion">
                {% if form.errors %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">
                        {{ form.errors }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
        <div class="register-card">
            <form action="{% url 'users:registration' %}" method="post" class="form-login">
                {% csrf_token %}
                <p>Регистрация</p>
                <div class="container-register">
                    <div class="col-1">
                        {{form.first_name}}
                        {{form.last_name}}
                        {{form.surname}}
                        {{form.number_class}}
                    </div>
                    <div class="col-2">
                        {{form.username}}
                        {{form.email}}
                        {{form.password1}}
                        {{form.password2}}
                    </div>
                </div>
                {{form.school}}
                <div class="for-teacher">
                    {{form.is_teacher}}
                    <p>Являюсь учителем</p>
                </div>
                <button type="submit" class="button-form">Зарегистрироваться</button>
            </form>
        </div>
</section>
{% endblock %}